
excluded_paths: [vendor/*, tests/*]

tools:
    php_cpd:
        command: phpcpd
        excluded_dirs: ["vendor", "tests"]

    php_code_sniffer:
        extensions:
            - php
        command: phpcs
        enabled: true
        filter:
            paths: ["app/src/*"]
        config:
            standard: Zend

    php_code_coverage:
        test_command: phpunit -c tests/phpunit.xml

    php_mess_detector: true
    php_analyzer: true
    sensiolabs_security_checker: true