


tools:
    php_cpd:
        command: phpcpd
        filter:
            excluded_paths: [vendor/*, tests/*]

    php_code_sniffer:
        extensions:
            - php
        command: phpcs
        enabled: true
        config:
            standard: Zend

    php_code_coverage:
        test_command: phpunit -c tests/phpunit.xml

    php_mess_detector: true
        filter:
            excluded_paths: [vendor/*, tests/*]
    php_analyzer: true
        filter:
            excluded_paths: [vendor/*, tests/*]
    sensiolabs_security_checker: true
        filter:
            excluded_paths: [vendor/*, tests/*]