# https://scrutinizer-ci.com/g/PHPocket/Widgets/

# tools config
tools:
    php_cpd:
        command: phpcpd
        filter:
            excluded_paths: [vendor, tests]

    php_code_sniffer:
        extensions:
            - php
        command: phpcs
        enabled: true
        config:
            standard: Zend
        filter:
            excluded_paths: [vendor, tests]

    php_code_coverage:
        test_command: phpunit -c tests/phpunit.xml

    php_mess_detector:
        filter:
            excluded_paths: [vendor, tests]
    php_analyzer:
        filter:
            excluded_paths: [vendor, tests]
    sensiolabs_security_checker:
        filter:
            excluded_paths: [vendor, tests]